include ../../Config.mk

MODULE_DEPS = $(LIBC_COMPONENT) $(LIBSTDCXX_COMPONENT) libpp_base

testtool_MODULE_NAME = test_log

TARGET_PRGS = testtool

testtool_SRCS = testtool.cpp
testtool_LIBS = -lpp_base

include $(PP_BUILD_SYS_DIR)/Top.mk
